// GENERAL_INFORMATION — Expanded Test Library (Super Detailed)
// Naming convention:
// - test_id: GI01, GI02, ...
// - category fixed to "GENERAL_INFORMATION"
// - severity_default: "B" for blocking/legal/identity errors; "C" for presentation-only issues
// - evidence_required: indicates what the AI MUST use/cite (pdf_text/pdf_images/portalData)
// Notes:
// - Any test requiring arithmetic should be JS-first. General Information should be extraction/consistency focused.

const generalTests = [
  {
    test_id: "GI01",
    category: "GENERAL",
    test_name: "ENTITY_LEGAL_NAME_PRESENT",
    severity_default: "B",
    evidence_required: ["pdf_text"],
    test_instructions: [
      "Locate the legal entity name as shown in the financial statements (typically cover page, headings, or general information section).",
      "Confirm the entity name is explicitly present (not blank, not truncated).",
      "Capture exact text as shown and cite page_no.",
      "If multiple name variants appear (e.g., short name vs full legal name), list all variants and flag potential inconsistency for GI03.",
    ],
  },
  {
    test_id: "GI02",
    category: "GENERAL",
    test_name: "ENTITY_REGISTRATION_NUMBER_PRESENT",
    severity_default: "B",
    evidence_required: ["pdf_text"],
    test_instructions: [
      "Locate the company registration number (e.g., Malta C-number) in the FS (cover/general info/audit report).",
      "Confirm it is explicitly present and not partially missing.",
      "Capture the exact registration number string and cite page_no.",
      "If no registration number is present anywhere in the FS, flag as missing mandatory identity element.",
    ],
  },
  {
    test_id: "GI03",
    category: "GENERAL",
    test_name: "ENTITY_NAME_CONSISTENT_ACROSS_DOCUMENT",
    severity_default: "B",
    evidence_required: ["pdf_text"],
    test_instructions: [
      "Compare the entity name across key sections:",
      "- Cover page",
      "- Contents page (if it mentions entity name)",
      "- Primary statement headings (Income statement, Balance sheet/SFP)",
      "- Notes headings (Notes to the financial statements)",
      "- Audit report (if present)",
      "Names must be consistent. Minor typography differences are acceptable ONLY if they do not change legal identity (e.g., spacing).",
      "If 'Limited' vs 'Ltd' discrepancy exists, flag as inconsistency unless the document uses one consistently and matches portal/MBR in GI10.",
      "Cite page_no for each distinct variant found.",
    ],
  },
  {
    test_id: "GI04",
    category: "GENERAL",
    test_name: "ENTITY_REGISTRATION_NUMBER_CONSISTENT_ACROSS_DOCUMENT",
    severity_default: "B",
    evidence_required: ["pdf_text"],
    test_instructions: [
      "If registration number appears in multiple places (cover, general info, audit report), verify exact match across all occurrences.",
      "Any mismatch in any digit/character is a critical identity error.",
      "Cite all page_no locations where the number appears.",
    ],
  },
  {
    test_id: "GI05",
    category: "GENERAL",
    test_name: "REGISTERED_OFFICE_ADDRESS_PRESENT",
    severity_default: "B",
    evidence_required: ["pdf_text"],
    test_instructions: [
      "Locate the registered office address (or principal place of business address) in the FS.",
      "Confirm address is present and not omitted.",
      "Capture the address exactly as displayed including line breaks if available, and cite page_no.",
      "If address is present but clearly incomplete (e.g., missing locality/country when used elsewhere), flag as issue.",
    ],
  },
  {
    test_id: "GI06",
    category: "GENERAL",
    test_name: "ADDRESS_CONSISTENT_ACROSS_DOCUMENT",
    severity_default: "B",
    evidence_required: ["pdf_text"],
    test_instructions: [
      "Compare address occurrences across:",
      "- General information section",
      "- Audit report (if present)",
      "- Any director/company information block",
      "Address must match line-by-line content and order where possible.",
      "If formatting differs but content matches (e.g., comma vs new line), mark as non-blocking (C).",
      "If content differs (street/locality/postcode/country mismatch), mark as critical (B).",
      "Cite page_no for each occurrence.",
    ],
  },
  {
    test_id: "GI07",
    category: "GENERAL",
    test_name: "LEGAL_FORM_SUFFIX_PRESENT_AND_CONSISTENT",
    severity_default: "B",
    evidence_required: ["pdf_text"],
    test_instructions: [
      "Verify the legal form suffix is present and consistent (e.g., 'Limited', 'Ltd').",
      "If the suffix is missing in primary headings but present elsewhere, flag as inconsistency.",
      "If the suffix differs across sections (e.g., Limited vs PLC), flag as critical identity error.",
      "Cite page_no evidence.",
    ],
  },
  {
    test_id: "GI08",
    category: "GENERAL",
    test_name: "FINANCIAL_PERIOD_END_DATE_PRESENT",
    severity_default: "B",
    evidence_required: ["pdf_text"],
    test_instructions: [
      "Extract the period end date from:",
      "- Cover page",
      "- Income statement heading (e.g., 'for the year ended ...')",
      "- Balance sheet heading (e.g., 'as at ...')",
      "- Audit report reference (if present)",
      "Confirm the date is explicitly stated at least once for each primary statement.",
      "If any primary statement lacks a date, flag as critical.",
      "Cite page_no for each extracted date.",
    ],
  },
  {
    test_id: "GI09",
    category: "GENERAL",
    test_name: "FINANCIAL_PERIOD_END_DATE_CONSISTENT_ACROSS_DOCUMENT",
    severity_default: "B",
    evidence_required: ["pdf_text"],
    test_instructions: [
      "Compare all extracted period end dates and balance sheet dates across the FS.",
      "They must match exactly for the current year set.",
      "If Income Statement date and Balance Sheet date refer to different year ends without explicit explanation, flag as critical.",
      "Cite page_no for each date instance.",
    ],
  },
  {
    test_id: "GI10",
    category: "GENERAL",
    test_name: "MBR_PORTAL_ENTITY_NAME_REG_NUMBER_ADDRESS_MATCH",
    severity_default: "B",
    evidence_required: ["pdf_text", "portalData.company"],
    test_instructions: [
      "Compare FS entity identifiers to portalData.company (MBR extract):",
      "- Company legal name exact match",
      "- Registration number exact match",
      "- Address line-by-line content and order match",
      "Any mismatch in name or registration number = critical error.",
      "Address mismatch: if content differs materially = critical; if formatting only differs = non-blocking (C) but still record.",
      "Cite FS page_no evidence and reference portalData.company fields used.",
    ],
  },
  {
    test_id: "GI11",
    category: "GENERAL",
    test_name: "DIRECTORS_LIST_PRESENT",
    severity_default: "B",
    evidence_required: ["pdf_text", "portalData.company"],
    test_instructions: [
      "Locate the directors list in the FS (general information/directors' responsibilities/audit report).",
      "Confirm at least one director is named.",
      "Compare count and names to portalData.company directors list if provided.",
      "Missing directors list in FS = critical (B) if portal/MBR indicates directors exist.",
      "Cite page_no for each director list occurrence.",
    ],
  },
  {
    test_id: "GI12",
    category: "GENERAL",
    test_name: "DIRECTORS_NAMES_MATCH_MBR_PORTAL",
    severity_default: "B",
    evidence_required: ["pdf_text", "portalData.company"],
    test_instructions: [
      "Compare director names shown in FS to portalData.company directors list.",
      "Names must match (allow minor formatting such as middle initial ordering only if clearly the same person).",
      "If any director is missing from FS or an extra director is listed in FS not in MBR, flag as critical identity/compliance error.",
      "Cite page_no and list mismatches explicitly.",
    ],
  },
  {
    test_id: "GI13",
    category: "GENERAL",
    test_name: "DIRECTORS_COUNT_DRIVES_GRAMMAR_CONSISTENCY",
    severity_default: "C",
    evidence_required: ["pdf_text", "portalData.company"],
    test_instructions: [
      "Based on MBR/portal directors count:",
      "- If 1 director, wording should be singular (e.g., 'the director').",
      "- If multiple directors, wording should be plural (e.g., 'the directors').",
      "Scan key narrative sections for mismatch (directors' responsibilities, approval statement, audit report responsibilities wording).",
      "If grammar mismatch could cause legal ambiguity, escalate to B; otherwise C.",
      "Cite page_no examples.",
    ],
  },
  {
    test_id: "GI14",
    category: "GENERAL",
    test_name: "COMPANY_STATUS_DISCLOSED_AND_ALIGNED_WITH_MBR",
    severity_default: "B",
    evidence_required: ["pdf_text", "portalData.company"],
    test_instructions: [
      "Check portalData.company status (e.g., active / in liquidation) if available.",
      "If MBR indicates liquidation:",
      "- FS basis should reflect liquidation basis, not going concern.",
      "- Audit report wording should reflect liquidation basis where applicable.",
      "If MBR indicates active:",
      "- FS can be going concern unless other triggers exist (handled elsewhere).",
      "If status basis is inconsistent, flag critical.",
      "Cite page_no evidence for status/basis wording.",
    ],
  },
  {
    test_id: "GI15",
    category: "GENERAL",
    test_name: "CURRENCY_DISCLOSURE_PRESENT",
    severity_default: "B",
    evidence_required: ["pdf_text"],
    test_instructions: [
      "Confirm the financial statements disclose the presentation currency (e.g., Euro/EUR).",
      "Acceptable locations: accounting policies, notes, general information, statement headings.",
      "If currency is not disclosed anywhere, flag as critical.",
      "Cite page_no and exact wording.",
    ],
  },
  {
    test_id: "GI16",
    category: "GENERAL",
    test_name: "CURRENCY_SYMBOL_USAGE_CONSISTENT",
    severity_default: "C",
    evidence_required: ["pdf_text", "pdf_images"],
    test_instructions: [
      "Check consistency of currency representation:",
      "- € symbol usage",
      "- 'EUR' usage",
      "- 'Euro' wording",
      "Inconsistency is non-blocking unless it causes ambiguity about unit/currency (then escalate to B).",
      "Cite page_no evidence.",
    ],
  },
  {
    test_id: "GI17",
    category: "GENERAL",
    test_name: "ROUNDING_POLICY_DISCLOSED_IF_APPLICABLE",
    severity_default: "C",
    evidence_required: ["pdf_text"],
    test_instructions: [
      "Determine whether figures appear rounded (e.g., to nearest euro, nearest thousand) based on presentation patterns (many trailing zeros, headings stating '€000').",
      "If rounding appears used, verify a rounding policy note exists (e.g., 'amounts are rounded to the nearest euro').",
      "If rounding appears used but no rounding disclosure exists, flag as non-blocking (C) unless rounding causes mismatches in cross-ties (handled elsewhere).",
      "Cite page_no evidence.",
    ],
  },
  {
    test_id: "GI18",
    category: "GENERAL",
    test_name: "ROUNDING_UNIT_INDICATION_CONSISTENT",
    severity_default: "B",
    evidence_required: ["pdf_text"],
    test_instructions: [
      "Check unit indicators such as:",
      "- '€', '€000', '€’000', 'EUR', 'Amounts in euro'",
      "Unit indicators must be consistent across primary statements and major notes tables.",
      "If income statement is in €000 but balance sheet appears in € (or vice versa) without explicit disclosure, flag as critical (B).",
      "Cite page_no evidence.",
    ],
  },
  {
    test_id: "GI19",
    category: "GENERAL",
    test_name: "COMPARATIVE_PERIOD_LABEL_PRESENT",
    severity_default: "B",
    evidence_required: ["pdf_text"],
    test_instructions: [
      "Confirm the comparative period is clearly labelled in the financial statements (e.g., year ended 20X1 comparatives).",
      "At minimum, primary statements must have a comparative column label or clearly indicated prior year.",
      "Missing comparative labels = critical (B).",
      "Cite page_no evidence.",
    ],
  },
  {
    test_id: "GI20",
    category: "GENERAL",
    test_name: "COMPARATIVE_YEAR_END_CONSISTENT",
    severity_default: "B",
    evidence_required: ["pdf_text"],
    test_instructions: [
      "Extract prior year comparative year-end date labels from primary statements and audit report references.",
      "Confirm prior year date is consistent across statements.",
      "If comparatives reference different year ends without explicit explanation, flag critical (B).",
      "Cite page_no evidence.",
    ],
  },
  {
    test_id: "GI21",
    category: "GENERAL",
    test_name: "DOCUMENT_TITLE_AND_DESCRIPTOR_PRESENT",
    severity_default: "C",
    evidence_required: ["pdf_text"],
    test_instructions: [
      "Confirm the document is clearly titled as financial statements (e.g., 'Financial Statements', 'Annual Report and Financial Statements').",
      "If title is missing or unclear, flag as non-blocking (C) unless it creates legal ambiguity about what the document is (then B).",
      "Cite page_no evidence.",
    ],
  },
  {
    test_id: "GI22",
    category: "GENERAL",
    test_name: "ACCOUNTING_FRAMEWORK_REFERENCE_PRESENT",
    severity_default: "B",
    evidence_required: ["pdf_text"],
    test_instructions: [
      "Check for explicit mention of the accounting framework used (e.g., GAPSME Malta) in accounting policies or notes.",
      "If the framework is not referenced anywhere, flag as critical (B) because users cannot determine the basis of preparation.",
      "Cite page_no and exact wording.",
    ],
  },
  {
    test_id: "GI23",
    category: "GENERAL",
    test_name: "BASIS_OF_PREPARATION_PRESENT",
    severity_default: "B",
    evidence_required: ["pdf_text"],
    test_instructions: [
      "Confirm a 'Basis of preparation' note exists (typically Note 1) describing how statements are prepared.",
      "If absent, flag as critical (B).",
      "Cite page_no and section/note reference.",
    ],
  },
  {
    test_id: "GI24",
    category: "GENERAL",
    test_name: "GOING_CONCERN_BASIS_WORDING_PRESENT",
    severity_default: "C",
    evidence_required: ["pdf_text"],
    test_instructions: [
      "Check basis of preparation includes going concern statement where appropriate (even if no triggers exist).",
      "If missing and no triggers exist, mark as C.",
      "If triggers exist, the dedicated going concern trigger test (cross/notes) will escalate to B; still record missing basis wording here if detected.",
      "Cite page_no evidence.",
    ],
  },
  {
    test_id: "GI25",
    category: "GENERAL",
    test_name: "APPROVAL_STATEMENT_PRESENT",
    severity_default: "B",
    evidence_required: ["pdf_text"],
    test_instructions: [
      "Locate a director approval statement for the balance sheet / financial statements.",
      "Confirm it explicitly indicates approval by the director(s) and includes a date and signature line(s).",
      "Missing approval statement or missing signature line(s) = critical (B).",
      "Cite page_no evidence.",
    ],
  },
  {
    test_id: "GI26",
    category: "GENERAL",
    test_name: "APPROVAL_DATE_PRESENT_AND_PARSEABLE",
    severity_default: "B",
    evidence_required: ["pdf_text"],
    test_instructions: [
      "Extract approval date from approval statement or signature block.",
      "Confirm it is present and parseable as a date.",
      "If multiple approval dates appear, flag inconsistency (B).",
      "Cite page_no evidence.",
    ],
  },
  {
    test_id: "GI27",
    category: "GENERAL",
    test_name: "DIRECTOR_SIGNATURE_PRESENT",
    severity_default: "B",
    evidence_required: ["pdf_text", "pdf_images"],
    test_instructions: [
      "Confirm director signature block exists with director name(s) and signature line(s).",
      "If images available, confirm there is a signed/marked signature area (visual).",
      "If not signed (blank line) where signature is expected, flag as critical (B).",
      "Cite page_no evidence.",
    ],
  },
  {
    test_id: "GI28",
    category: "GENERAL",
    test_name: "DIRECTOR_NAME_IN_SIGNATURE_MATCHES_DIRECTORS_LIST",
    severity_default: "B",
    evidence_required: ["pdf_text", "portalData.company"],
    test_instructions: [
      "Extract director name(s) shown in signature/approval block.",
      "Compare to directors list in FS and to portalData.company directors list.",
      "Any mismatch in named approving director(s) = critical (B).",
      "Cite page_no evidence.",
    ],
  },
  {
    test_id: "GI29",
    category: "GENERAL",
    test_name: "AUDIT_REPORT_EXPECTATION_AND_PRESENCE_FLAG",
    severity_default: "B",
    evidence_required: ["pdf_text", "portalData"],
    test_instructions: [
      "Determine whether an audit report is expected based on engagement/portal context if provided.",
      "If audit report is expected, verify an audit report section exists in the PDF.",
      "If expected but missing, flag critical (B).",
      "If present, record page_no start for use in audit report category tests.",
    ],
  },
  {
    test_id: "GI30",
    category: "GENERAL",
    test_name: "TERMINOLOGY_AUDITORS_REPORT_SPELLING",
    severity_default: "C",
    evidence_required: ["pdf_text"],
    test_instructions: [
      "Check for terminology usage: must use 'auditors' report' (plural possessive) not 'auditor's report'.",
      "If incorrect usage appears, flag as non-blocking presentation issue (C) unless it creates legal ambiguity about the report identity (then B).",
      "Cite page_no evidence.",
    ],
  },
  {
    test_id: "GI31",
    category: "GENERAL",
    test_name: "DOCUMENT_PAGE_COUNT_AND_INTERNAL_REFERENCES",
    severity_default: "C",
    evidence_required: ["pdf_text"],
    test_instructions: [
      "If the document states total pages (e.g., 'Page X of Y' or similar), verify that Y matches the actual page count from input data.",
      "If mismatch, flag as issue (C) unless it indicates missing/duplicated page content (then B).",
      "Cite page_no evidence.",
    ],
  },
  {
    test_id: "GI32",
    category: "GENERAL",
    test_name: "CONFIDENTIALITY_OR_INTERNAL_USE_LABELS_DO_NOT_CONFLICT",
    severity_default: "C",
    evidence_required: ["pdf_text"],
    test_instructions: [
      "Check for document labels such as 'Draft', 'Unaudited', 'For internal use only', 'Confidential'.",
      "If an audit report/opinion is present, 'Draft/Unaudited' labels may conflict and should be flagged.",
      "Classify as B only if it creates a clear contradiction with signing/approval (e.g., audited opinion + 'unaudited' cover). Otherwise C.",
      "Cite page_no evidence.",
    ],
  },
  {
    test_id: "GI33",
    category: "GENERAL",
    test_name: "LANGUAGE_CONSISTENCY_FOR_KEY_LABELS",
    severity_default: "C",
    evidence_required: ["pdf_text"],
    test_instructions: [
      "Check that key labels are consistent across the FS (e.g., 'Statement of Financial Position' vs 'Balance Sheet').",
      "If multiple labels are used inconsistently without reason, flag as C.",
      "Escalate to B only if it creates ambiguity about which statement is which (rare).",
      "Cite page_no evidence.",
    ],
  },
  {
    test_id: "GI34",
    category: "GENERAL",
    test_name: "PRESENTATION_OF_NEGATIVES_CONSISTENT_GLOBALLY",
    severity_default: "C",
    evidence_required: ["pdf_text", "pdf_images"],
    test_instructions: [
      "Check consistent representation of negative numbers across the document:",
      "- Brackets ( )",
      "- Minus sign -",
      "- Red text (if observable via images)",
      "Inconsistent negative presentation is C unless it causes ambiguity/misstatement risk (e.g., negative shown as positive due to missing brackets) then B.",
      "Cite page_no evidence.",
    ],
  },
  {
    test_id: "GI35",
    category: "GENERAL",
    test_name: "THOUSANDS_SEPARATOR_AND_DECIMAL_STYLE_CONSISTENT",
    severity_default: "C",
    evidence_required: ["pdf_text"],
    test_instructions: [
      "Check that thousands separators and decimals follow a consistent style (e.g., 1,000 vs 1 000; decimals '.' vs ',').",
      "If mixed styles appear and could lead to numeric misreading, escalate to B; otherwise C.",
      "Cite page_no evidence.",
    ],
  },
];

const generalPrompt = `
  the tests are to run against the general information.
  ${generalTests.map(test => `- ${test.test_name}`).join('\n')}
`;

module.exports = {
  generalTests,
  generalPrompt,
};
